In [26]:
import pandas as pd

**SWCPQ**

In [27]:
import re

with open("key.js", encoding="utf-8") as f:
    js = f.read()

section = js.split("var measures = {", 1)[1].split("};", 1)[0]

pattern = r'(\d+)\s*:\s*\["([^"]*)",\s*"([^"]*)"\]'
matches = re.findall(pattern, section)

traits_df = pd.DataFrame(matches, columns=["trait_id", "trait_low", "trait_high"])

traits_df["trait_id"] = traits_df["trait_id"].astype(int)
traits_df = traits_df[traits_df["trait_id"].between(1, 525)]

#traits_df["column_name"] = "BAP" + traits_df["trait_id"].astype(str)

traits_df

     trait_id  trait_low trait_high
0           1    playful    serious
1           2        shy       bold
2           3     cheery  sorrowful
3           4  masculine   feminine
4           5   charming    awkward
..        ...        ...        ...
520       521     fickle     steady
521       522      shaky       firm
522       523       numb    dynamic
523       524      sharp       dull
524       525      zesty      stale

[525 rows x 3 columns]

In [15]:
with open("key.js", encoding="utf-8") as f:
    js = f.read()

section = js.split("var subjects =", 1)[1]

pattern = r'"([^"]+)"\s*:\s*\{\s*((?:(?!\n\s*"\w+"\s*:\s*\{).)*)'

characters = []

for work_code, body in re.findall(pattern, section, re.S):
    names = re.findall(
        r'(\d+)\s*:\s*\["([^"]+)",\s*"([^"]+)"\]',
        body
    )

    for char_id, name, image in names:
        characters.append({
            "character_code": f"{work_code}/{char_id}",
            "character_name": name,
            "image": image,
            "work_code": work_code
        })

character_df = pd.DataFrame(characters)
character_df[["character_code","character_name"]]

     character_code      character_name
0             GOT/1            Jon Snow
1             GOT/2    Tyrion Lannister
2             GOT/3  Daenerys Targaryen
3             GOT/4         Sansa Stark
4             GOT/5          Arya Stark
...             ...                 ...
2237           LB/1          Elle Woods
2238          BGN/1     Michelle Fuller
2239          BGN/2          Teddy Gatz
2240          PHM/1        Ryland Grace
2241          PHM/2               Rocky

[2242 rows x 2 columns]

In [16]:
with open("characterScores2125x525.js", "r", encoding="utf-8") as f:
    with open("characterScores.txt", "w", encoding="utf-8") as fw:
        for i in range(2200):
            content = f.readline()
            content = content.replace("[", "")
            content = content.replace("]", "")
            content = content.replace(";", "")
            content = content.replace("{", "")
            content = content.replace("}", "")
            content = content.replace(": ", ",")
    
            

            if(i==0):
                fw.write(content[:-1]+'\n')
                #print(content[:-1])
            else:
                fw.write(content[:-2]+'\n')
                #print(content[:-2])

In [17]:
scores_df = pd.read_csv("characterScores.txt",sep=',')
print(scores_df.shape)
scores_df

(2125, 526)

,character,1,2,3,4,5,6,7,8,9,...,516,517,518,519,520,521,522,523,524,525
0,HML/1,60,67,92,33,57,53,27,44,61,...,17,44,38,16,34,37,40,79,20,43
1,HML/2,75,60,69,78,36,42,42,40,23,...,59,58,45,16,59,40,64,42,68,76
2,HML/3,84,85,69,20,40,36,51,16,59,...,44,43,45,12,25,35,64,34,43,65
3,HML/4,72,65,67,28,66,47,29,19,34,...,28,50,34,35,44,63,52,59,44,63
4,HML/5,39,45,81,90,55,59,41,73,44,...,24,39,22,38,76,20,25,42,49,52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2120,S8/6,27,71,40,46,18,55,80,72,55,...,41,25,23,18,29,46,38,79,38,15
2121,S8/7,79,76,57,17,35,66,66,33,60,...,44,59,25,43,26,84,85,61,28,47
2122,S8/8,78,79,70,74,48,52,32,37,31,...,34,24,40,22,54,41,60,67,27,40
2123,S8/9,17,94,13,64,22,50,30,74,65,...,59,45,26,53,39,66,70,87,22,6
2124,S8/10,55,45,38,42,33,83,23,64,21,...,21,70,39,80,33,75,59,69,32,17

In [18]:
scores_df['character'].isin(character_df['character_code']).all()    #all characters have a character_code

np.True_

**WikiData**

In [19]:
import requests

query = """
SELECT ?character ?characterLabel ?workLabel
WHERE {
  ?character wdt:P31/wdt:P279* wd:Q95074 .
  OPTIONAL {
    ?character wdt:P1441 ?work .
  }
  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "en".
  }
}
LIMIT 100
"""

url = "https://query.wikidata.org/sparql"

#response = requests.get(
#    url,
#    params={"query": query, "format": "json"},
#    headers={"User-Agent": "SWCPQResearch/1.0 (educational project)"}
#)

#response.raise_for_status()
#results = response.json()["results"]["bindings"]

#df = pd.json_normalize(results)

#df

#this can be very long

**O*NET**

In [20]:
onet = pd.read_csv("work_styles.csv")

In [21]:
onet

,O*NET-SOC Code,Title,Element ID,Element Name,Scale ID,Scale Name,Data Value,Date,Domain Source
0,11-1011.00,Chief Executives,1.D.1.a,Innovation,DR,Distinctiveness Rank,7.00,12/2025,AI/Expert
1,11-1011.00,Chief Executives,1.D.1.a,Innovation,WI,Work Styles Impact,2.30,12/2025,AI/Expert
2,11-1011.00,Chief Executives,1.D.1.b,Achievement Orientation,DR,Distinctiveness Rank,0.00,12/2025,AI/Expert
3,11-1011.00,Chief Executives,1.D.1.b,Achievement Orientation,WI,Work Styles Impact,2.91,12/2025,AI/Expert
4,11-1011.00,Chief Executives,1.D.1.c,Intellectual Curiosity,DR,Distinctiveness Rank,0.00,12/2025,AI/Expert
...,...,...,...,...,...,...,...,...,...
37417,53-7121.00,"Tank Car, Truck, and Ship Loaders",1.D.3.d,Integrity,WI,Work Styles Impact,1.60,12/2025,AI/Expert
37418,53-7121.00,"Tank Car, Truck, and Ship Loaders",1.D.4.a,Stress Tolerance,DR,Distinctiveness Rank,0.00,12/2025,AI/Expert
37419,53-7121.00,"Tank Car, Truck, and Ship Loaders",1.D.4.a,Stress Tolerance,WI,Work Styles Impact,1.35,12/2025,AI/Expert
37420,53-7121.00,"Tank Car, Truck, and Ship Loaders",1.D.4.b,Self-Control,DR,Distinctiveness Rank,0.00,12/2025,AI/Expert
37421,53-7121.00,"Tank Car, Truck, and Ship Loaders",1.D.4.b,Self-Control,WI,Work Styles Impact,1.03,12/2025,AI/Expert

In [22]:
#Example
job_title = "Nuclear Engineers"

filtered = onet[(onet["Scale Name"] == "Work Styles Impact") & (onet["Title"].str.casefold() == job_title.casefold())]
filtered = filtered.sort_values(by="Data Value", ascending=False)

print(filtered[["Element Name", "Data Value"]])

                 Element Name  Data Value
6503            Dependability        3.00
6501      Attention to Detail        3.00
6505                Integrity        2.93
6499             Cautiousness        2.74
6473   Intellectual Curiosity        2.58
6509             Self-Control        2.50
6507         Stress Tolerance        2.39
6471  Achievement Orientation        2.21
6483             Perseverance        2.12
6469               Innovation        1.97
6481          Self-Confidence        1.73
6485   Leadership Orientation        1.58
6479             Adaptability        1.48
6493              Cooperation        1.44
6477               Initiative        1.38
6475  Tolerance for Ambiguity        1.37
6489                Sincerity        1.19
6487                 Humility        0.64
6497       Social Orientation        0.29
6495                 Optimism        0.13
6491                  Empathy        0.12

In [23]:
jobs = onet[["O*NET-SOC Code","Title"]]
jobs.drop_duplicates()

      O*NET-SOC Code                                             Title
0         11-1011.00                                  Chief Executives
42        11-1021.00                   General and Operations Managers
84        11-1031.00                                       Legislators
126       11-2011.00               Advertising and Promotions Managers
168       11-2021.00                                Marketing Managers
...              ...                                               ...
37212     53-7071.00  Gas Compressor and Gas Pumping Station Operators
37254     53-7072.00           Pump Operators, Except Wellhead Pumpers
37296     53-7073.00                                  Wellhead Pumpers
37338     53-7081.00         Refuse and Recyclable Material Collectors
37380     53-7121.00                 Tank Car, Truck, and Ship Loaders

[891 rows x 2 columns]

In [24]:
traits = onet[["Element ID","Element Name"]]
traits.drop_duplicates()

   Element ID             Element Name
0     1.D.1.a               Innovation
2     1.D.1.b  Achievement Orientation
4     1.D.1.c   Intellectual Curiosity
6     1.D.1.d  Tolerance for Ambiguity
8     1.D.1.e               Initiative
10    1.D.1.f             Adaptability
12    1.D.1.g          Self-Confidence
14    1.D.1.h             Perseverance
16    1.D.1.i   Leadership Orientation
18    1.D.2.a                 Humility
20    1.D.2.b                Sincerity
22    1.D.2.c                  Empathy
24    1.D.2.d              Cooperation
26    1.D.2.e                 Optimism
28    1.D.2.f       Social Orientation
30    1.D.3.a             Cautiousness
32    1.D.3.b      Attention to Detail
34    1.D.3.c            Dependability
36    1.D.3.d                Integrity
38    1.D.4.a         Stress Tolerance
40    1.D.4.b             Self-Control

In [28]:
jon = scores_df[scores_df["character"] == "GOT/1"].iloc[0, 1:].astype(float).values
out = traits_df.copy()
out["score"] = jon
out.sort_values("score").head(5)    # closest to the LOW pole

     trait_id       trait_low      trait_high  score
217       218      persistent         quitter    7.0
400       401  main character  side character    8.0
363       364         devoted      unfaithful    9.0
519       520     deep-voiced     high-voiced    9.0
31         32        diligent            lazy    9.0

In [30]:
jon = scores_df[scores_df["character"] == "HP/1"].iloc[0, 1:].astype(float).values
out = traits_df.copy()
out["score"] = jon
out.sort_values("score").tail(5)

     trait_id trait_low  trait_high  score
212       213  studious    goof-off   85.0
160       161   captain  first-mate   86.0
414       415   thinker      feeler   86.0
149       150      neat       messy   86.0
444       445  clinical   heartfelt   87.0

In [31]:
character_df[character_df["character_name"].str.contains("Hermione")]

    character_code    character_name      image work_code
32            HP/3  Hermione Granger   HP/3.jpg        HP
823          RD/11    Hermione Lodge  RD/11.jpg        RD